int* encode(char*, int*, int);
void change(int*, int, int, int);
void cumulative_sum(int*, int);
int** transpose(int*, int**, int, int);
int* map_change(int*, int*, int);
int* modular_subtraction_digit(int*, int*, int);
int* modular_addition_digit(int*, int*, int);
int* assign_char(char*, int, int, int);
int* assign_int(int*, int, int);
int* chain_addition(int* , int);
int* join(int*, int, int*, int);
